"""add_emergency_contact_to_users

Revision ID: 0230216f4fdc
Revises: b7894161f34f
Create Date: 2026-05-19 19:36:18.132711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0230216f4fdc'
down_revision = 'b7894161f34f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emergency_contact_phone')
    op.drop_column('users', 'emergency_contact_name')
    # ### end Alembic commands ###
